services:
  db: 
    image: postgres:latest
    container_name: my_db_compose
    ports:
       - "${DATABASE_PORT}:5432"
    environment:
       - POSTGRES_DB=${DATABASE_NAME}
       - POSTGRES_USER=${DATABASE_USER}
       - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
       - strapi-net

  app:
    image: prawee/strapi:latest
    container_name: my_app_compose
    ports:
      - "${APP_PORT}:1337"
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432   #ดูPORTดีดี#
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=false 

    depends_on:
      - db
    networks:
      - strapi-net

networks:
   strapi-net:
    driver: bridge
     